# Generated by Django 4.0.3 on 2022-04-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoptop', '0003_alter_product_category_alter_product_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
