# Generated by Django 4.0.3 on 2022-06-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoptop', '0005_contact_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_details', models.CharField(max_length=5000)),
                ('total_amount', models.CharField(max_length=70)),
                ('fname', models.CharField(max_length=70)),
                ('lname', models.CharField(max_length=70)),
                ('pnumber', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=70)),
                ('state', models.CharField(max_length=70)),
                ('zip', models.CharField(max_length=70)),
                ('date', models.DateField()),
            ],
        ),
    ]
